Tasks/asp/old hospital/АРМ робітника прийомного відділення/Controllers/HospitalizationController.cs
using System.Web.Mvc;
using Business_Layer.Manager;
using System.Net;
using Business_Layer.DataModels;
using System;

namespace АРМ_робітника_прийомного_відділення.Controllers
{
    public class HospitalizationController : Controller
    {
        private HospitalizationManager hospitalization = new HospitalizationManager();
        private HospitalizationDataModel hospitalizationmodel = new HospitalizationDataModel();

        public ActionResult HospitalizationGrid()
        {
            return View(hospitalization.GetListOfHospitalization());
        }


  
        public ActionResult HospitalizationGridWith()
        {
            return View(hospitalization.GetListOfHospitalizationWithPaz());
        }


        [HttpGet]
        public ActionResult CreateHospitalization(int? id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateHospitalization(int? id,[Bind(Include = "Number_of_hospitalization,Handling,Directional,Diagnosis_of_directional,Through_hours,Diagnosis_of_clinical,Diagnosis_of_conclusive,Diagnosis_of_hospitalization,Date_of_hospitalization,Number_of_med_cards,Reasons")] HospitalizationDataModel hospitalizationmodel)
        {
            if (ModelState.IsValid)
            {
                hospitalization.AddHospitalization(id,hospitalizationmodel);
                return RedirectToAction("HospitalizationGrid");
            }
            return View(hospitalizationmodel);
        }
        [Authorize(Roles = "admin")]
        public ActionResult DeleteHospitalization(int id)
        {
            try
            {
                hospitalization.DelRowById(id);
                return RedirectToAction("HospitalizationGrid");
            }
            catch
            {
                return View(hospitalizationmodel);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult EditHospitalization(int id)
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult EditHospitalization(int id, [Bind(Include = "Number_of_hospitalization,Handling,Directional,Diagnosis_of_directional,Through_hours,Diagnosis_of_clinical,Diagnosis_of_conclusive,Diagnosis_of_hospitalization,Date_of_hospitalization,Number_of_med_cards,Reasons")] HospitalizationDataModel hospitalizationmodel)
        {
            if (ModelState.IsValid)
            {
                hospitalization.EditPatientcategory(id, hospitalizationmodel);
                return RedirectToAction("HospitalizationGrid");
            }
            return View(hospitalizationmodel);
        }
    }
}

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Controllers/PatientController.cs
using System.Linq;
using System.Web.Mvc;
using Business_Layer.Manager;
using Business_Layer.DataModels;
using АРМ_робітника_прийомного_відділення.Filters;

namespace АРМ_робітника_прийомного_відділення.Controllers
{
    public class PatientController : Controller
    {
        private PatientManager patient = new PatientManager();
        private PatientDataModel patientmodel = new PatientDataModel();
        private CategoryManager category = new CategoryManager();
        private ContractsManager contract = new ContractsManager();

        public ActionResult PatientGrid()
        {
            return View(patient.GetListOfPatient());
        }

        [HttpGet]
        public ActionResult CreatePatient()
        {
            var model = category.GetListOfCategory().
                Select(x => new SelectListItem
                {
                    Text = x.Category_type,
                    Value = x.Number_of_category.ToString()
                }).ToList();
            ViewBag.CategoryTypesList = model;

            var model2 = contract.GetListOfContracts().
                Select(x => new SelectListItem
                {
                    Text = x.Number_of_contracts,
                    Value = x.Number_of_contracts
                }).ToList();
            ViewBag.ContractsTypesList = model2;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePatient([Bind(Include = "Number_of_med_cards,Name,Surname,Middle_name,Sex,Birthday,Position,Period_of_nutrition,Number_of_contracts,Number_of_category")] PatientDataModel patientmodel)
        {
            if (ModelState.IsValid)
            {
                patient.AddPatient(patientmodel);
                return RedirectToAction("PatientGrid");
            }
            return View(patientmodel);
        }

        [Authorize(Roles = "admin")]
        public ActionResult DeletePatient(int id)
        {
            try
            {
                patient.DelRowById(id);
                return RedirectToAction("PatientGrid");
            }
            catch
            {
                return View(patientmodel);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult EditPatient(int id)
        {
            var model = category.GetListOfCategory().
               Select(x => new SelectListItem
               {
                   Text = x.Category_type,
                   Value = x.Number_of_category.ToString()
               }).ToList();
            ViewBag.CategoryTypesList = model;

            var model2 = contract.GetListOfContracts().
                Select(x => new SelectListItem
                {
                    Text = x.Number_of_contracts,
                    Value = x.Number_of_contracts
                }).ToList();
            ViewBag.ContractsTypesList = model2;


            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult EditPatient(int id,[Bind(Include = "Number_of_med_cards,Name,Surname,Middle_name,Sex,Birthday,Position,Period_of_nutrition,Number_of_contracts,Number_of_category")] PatientDataModel patientmodel)
        {
            if (ModelState.IsValid)
            {
                patient.EditPatient(id,patientmodel);
                return RedirectToAction("PatientGrid");
            }
            return View(patientmodel);
        }
    }
}

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Patient/CreatePatient.cshtml
@model Business_Layer.DataModels.PatientDataModel

@{
    var list = (ViewBag.CategoryTypesList as List<SelectListItem>);
    if (list == null) { list = new List<SelectListItem>(); }

    var listcontracts = (ViewBag.ContractsTypesList as List<SelectListItem>);
    if (listcontracts == null) { listcontracts = new List<SelectListItem>(); }

}

<link href="~/Content/GridGround.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="white">
        <center>
            <div class="row">
                  <h2>Додати нового пацієнта</h2> 
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-6">
            <div class="form-horizontal">
              

                <div class="form-group">
                    <label class="control-label col-md-4">Ім'я</label>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Прізвище</label>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">По-батькові</label>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Middle_name, "{0:dd.MM.yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Middle_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Стать</label>
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Sex, new SelectList(
                        new List<Object>{
                        new { value="Жін" , text = "Жін"  },
                        new { value="Чол" , text = "Чол" } },
                       "value", "text"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">День народження</label>
                    <div class="col-md-6">
                        @Html.TextBoxFor(model => model.Birthday, "{dd.mm.yyyy}", new { @class = "form-control datepicker" })
                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            </div>

                <div class="col-md-6">
            <div class="form-horizontal">

                <div class="form-group">
                    <label class="control-label col-md-4">Посада</label>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Період харчування</label>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Period_of_nutrition, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Period_of_nutrition, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Контракт</label>
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Number_of_contracts, listcontracts, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Number_of_contracts, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Категорія</label>
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Number_of_category, list, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Number_of_category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Додати"  class="btn-info btn-lg" />
                    </div>
                    
                </div>
                <div>
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Сформувати медичну карту" class="btn-info btn-lg" />
                    </div>
                </div>
                </div>
                    </div>
                </div>
</center>
        </div>
            }
            @section Scripts {
<script type="text/javascript" src="~/Scripts/jquery-2.2.3.min.js"></script>
<script type="text/javascript" src="~/Scripts/moment-with-locales.min.js"></script>
                @Scripts.Render("~/bundles/jqueryval")
                @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
                @Styles.Render("~/Content/bootstrap-datepicker.css")


                <script type="text/javascript">
                    $(function () {
                        $('.datepicker').datepicker({
                            format: "dd.mm.yyyy",
                            autoclose: true,
                            language: 'ru'
                        });

                    });

                    $.fn.datepicker.dates['ru'] = {
                        days: ["Понеділок", "Вівторок", "Середа", "Четерг", "П'ятниця", "Субота", "Неділя"],
                        daysShort: ["Пон", "Вів", "Сер", "Чет", "П'ятн", "Суб", "Нед"],
                        daysMin: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
                        months: ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
                        monthsShort: ["Січ", "Лют", "Бер", "Квіт", "Трав", "Черв", "Лип", "Серп", "Верес", "Жовт", "Лист", "Груд"],
                        format: "mm.dd.yyyy",
                    };

                    $(function () {
                        $.validator.methods.date = function (value, element) {
                            if ($.browser.webkit) {
                                var d = new Date();
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                            }
                            else {
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                            }
                        };
                    });
                </script>

            }
          

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Patient/DeletePatient.cshtml
@model Business_Layer.DataModels.PatientDataModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PatientDataModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number_of_med_cards)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_med_cards)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Middle_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Middle_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Handling)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Handling)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period_of_nutrition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period_of_nutrition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_contracts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_contracts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_category)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
        </div>
    }
</div>

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Patient/EditPatient.cshtml
@model Business_Layer.DataModels.PatientDataModel

@{
    var list = (ViewBag.CategoryTypesList as List<SelectListItem>);
    if (list == null) { list = new List<SelectListItem>(); }

    var listcontracts = (ViewBag.ContractsTypesList as List<SelectListItem>);
    if (listcontracts == null) { listcontracts = new List<SelectListItem>(); }

    var listhandaling = (ViewBag.Handalin as List<SelectListItem>);
    if (listhandaling == null) { listhandaling = new List<SelectListItem>(); }
}

<link href="~/Content/GridGround.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="white">
        <center>
            <div class="row">
                <h2>Редагувати пацієнта</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-6">
                    <div class="form-horizontal">


                        <div class="form-group">
                            <label class="control-label col-md-4">Ім'я</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Прізвище</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">По-батькові</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Middle_name, "{0:dd.MM.yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Middle_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Стать</label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Sex, new SelectList(
                        new List<Object>{
                        new { value="Жін" , text = "Жін"  },
                        new { value="Чол" , text = "Чол" } },
                       "value", "text"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="control-label col-md-4">День народження</label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Birthday, "{0:dd.MM.yyyy}", new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="control-label col-md-4">Посада</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Період харчування</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Period_of_nutrition, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Period_of_nutrition, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Контракт</label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Number_of_contracts, listcontracts, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Number_of_contracts, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Категорія</label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Number_of_category, list, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Number_of_category, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Редагувати" class="btn-info btn-lg" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </center>
    </div>
}
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Styles.Render("~/Content/bootstrap-datepicker.css")

    <script src="~/Scripts/moment-with-locales.min.js"></script>

    <script type="text/javascript">
                    $(function () {
                        $('.datepicker').datepicker({
                            format: "dd.mm.yyyy",
                            autoclose: true,
                            language: 'ru'
                        });

                    });
    </script>

}

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Patient/PatientGrid.cshtml
@model IEnumerable<Business_Layer.DataModels.PatientDataModel>
@using GridMvc.Html
<meta name="viewport" content="width=device-width" />

@{
    ViewBag.Title = "PatientGrid";
}
<link href="~/Content/GridGround.css" rel="stylesheet" />
<div id="white">
    <center>
    <h2>Перелік пацієнтів</h2>
        
    @Html.Grid(Model).SetLanguage("uk").Columns(columns =>
{
    columns.Add(data => data.Number_of_med_cards).Titled(" № Мед карти").Filterable(true);
    columns.Add(data => data.Surname).Titled("ПІБ").RenderValueAs(o => o.Surname + " " + o.Name + " " + o.Middle_name).Filterable(true);
    columns.Add(data => data.Sex).Titled("Стать").Filterable(true);
    columns.Add(data => data.Birthday).Format("{0:dd/MM/yyyy}").Titled("День нар.").Filterable(true);
    columns.Add(data => data.Position).Titled("Посада").Filterable(true);
    columns.Add(data => data.Period_of_nutrition).Titled("Період харч.").Filterable(true);
    columns.Add(data => data.Number_of_contracts).Titled("№ Контракту").Filterable(true);
    columns.Add(data => data.Number_of_category).Titled("Категорія").Filterable(true);
    columns.Add()
                       .Encoded(false)
                       .Sanitized(false)
                        .SetWidth(30)
                       .RenderValueAs(o => Html.ActionLink("Госпіталізація", "CreateHospitalization", "Hospitalization", new { Name = "Example" }, new { id = o.Number_of_med_cards }));
    columns.Add()
                        .Encoded(false)
                        .Sanitized(false)
                        .SetWidth(30)
                        .RenderValueAs(o => Html.ActionLink("Редагувати", "EditPatient", new { id = o.Number_of_med_cards }));
    columns.Add()
                     .Encoded(false)
                     .Sanitized(false)
                     .SetWidth(30)
                     .RenderValueAs(o => Html.ActionLink("Видалити", "DeletePatient", new { id = o.Number_of_med_cards }));
}).WithPaging(4).Sortable(true).WithMultipleFilters()
</center>
</div>
@section Scripts {

@Scripts.Render("~/bundles/mvcgrid")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Styles.Render("~/Content/bootstrap-datepicker.css")
<link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" type="text/css" />


}