Tasks/asp/old hospital/АРМ робітника прийомного відділення/Controllers/StaffController.cs
using Business_Layer.DataModels;
using Business_Layer.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace АРМ_робітника_прийомного_відділення.Controllers
{
    public class StaffController : Controller
    {
        private StaffManager staff = new StaffManager();
        private StaffDataModel staffmodel = new StaffDataModel();

        public ActionResult StaffGrid()
        {
            return View(staff.GetListOfStaff());
        }

        [HttpGet]
        public ActionResult CreateStaff()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStaff([Bind(Include = "Number_of_staff,Name,Surname,Middle_name,Birthday,Employment_day,Addresses,Phone_number,Name_of_position")] StaffDataModel patientmodel)
        {
            if (ModelState.IsValid)
            {
                staff.AddStaff(patientmodel);
                return RedirectToAction("StaffGrid");
            }
            return View(patientmodel);
        }
        [Authorize(Roles = "admin")]
        public ActionResult DeleteStaff(int id)
        {
            try
            {
                staff.DelRowById(id);
                return RedirectToAction("StaffGrid");
            }
            catch
            {
                return View(staffmodel);
            }
        }
        [Authorize(Roles = "admin")]
        public ActionResult EditStaff(int id)
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult EditStaff(int id, [Bind(Include = "Number_of_staff,Name,Surname,Middle_name,Birthday,Employment_day,Addresses,Phone_number,Name_of_position")] StaffDataModel staffmodel)
        {
            if (ModelState.IsValid)
            {
                staff.EditStaff(id, staffmodel);
                return RedirectToAction("StaffGrid");
            }
            return View(staffmodel);
        }
    }
}

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Staff/CreateStaff.cshtml
@model Business_Layer.DataModels.StaffDataModel

<link href="~/Content/GridGround.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="white">
        <center>
            <div class="row">
                <h2>Додати нового працівника</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-6">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="control-label col-md-4">Ім'я</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Прізвище</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">По-батькові</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Middle_name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Middle_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">День народження</label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Birthday, "{0:dd.MM.yyyy}", new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="control-label col-md-4">День наймання на роботу</label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Employment_day, "{0:dd.MM.yyyy}", new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(model => model.Employment_day, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Адреса</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Addresses, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Addresses, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Телефон</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Phone_number, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Посада</label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Name_of_position, new SelectList(
                        new List<Object>{
                        new { value="Хірург" , text = "Хірург"  },
                        new { value="Педіатр" , text = "Педіатр"  },
                        new { value="Медсестра" , text = "Медсестра"  },
                        new { value="Терапевт" , text = "Терапевт"  },
                        new { value="Мед-сестра" , text = "Мед-сестра"  },
                         new { value="Санітарка" , text = "Санітарка"  },
                        new { value="Психолог" , text = "Психолог" } },
                       "value", "text"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name_of_position, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Додати" class="btn-info btn-lg" />
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </center>
            </div>
                    }
                    @section Scripts {

                        <script type="text/javascript" src="~/Scripts/jquery-2.2.3.min.js"></script>
<script type="text/javascript" src="~/Scripts/moment-with-locales.min.js"></script>
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/bootstrap-datepicker.js")
@Styles.Render("~/Content/bootstrap-datepicker.css")


<script type="text/javascript">
                    $(function () {
                        $('.datepicker').datepicker({
                            format: "dd.mm.yyyy",
                            autoclose: true,
                            language: 'ru'
                        });

                    });

                    $.fn.datepicker.dates['ru'] = {
                        days: ["Понеділок", "Вівторок", "Середа", "Четерг", "П'ятниця", "Субота", "Неділя"],
                        daysShort: ["Пон", "Вів", "Сер", "Чет", "П'ятн", "Суб", "Нед"],
                        daysMin: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
                        months: ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
                        monthsShort: ["Січ", "Лют", "Бер", "Квіт", "Трав", "Черв", "Лип", "Серп", "Верес", "Жовт", "Лист", "Груд"],
                        format: "mm.dd.yyyy",
                    };

                    $(function () {
                        $.validator.methods.date = function (value, element) {
                            if ($.browser.webkit) {
                                var d = new Date();
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                            }
                            else {
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                            }
                        };
                    });
</script>
                    }

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Staff/DeleteStaff.cshtml
@model Business_Layer.DataModels.StaffDataModel

@{
    ViewBag.Title = "DeleteStaff";
}

<h2>DeleteStaff</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StaffDataModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number_of_staff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_staff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Middle_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Middle_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employment_day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employment_day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addresses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addresses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name_of_position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_of_position)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Staff/EditStaff.cshtml
@model Business_Layer.DataModels.StaffDataModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>StaffDataModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Ім'я</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Прізвище</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">По-батькові</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Middle_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Middle_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">День народження</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Birthday, "{0:dd.MM.yyyy}", new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">День наймання на роботу</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Employment_day, "{0:dd.MM.yyyy}", new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.Employment_day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Адреса</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addresses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Addresses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Телефон</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Посада</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Name_of_position, new SelectList(
                        new List<Object>{
                        new { value="Лікар" , text = "Хірург"  },
                        new { value="Лікар" , text = "Педіатр"  },
                        new { value="Лікар" , text = "Медсестра"  },
                        new { value="Лікар" , text = "Терапевт"  },
                        new { value="Лікар" , text = "Мед-сестра"  },
                         new { value="Лікар" , text = "Санітарка"  },
                        new { value="Повторно" , text = "Психолог" } },
                       "value", "text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name_of_position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Перегляд робітників", "StaffGrid", "Staff")
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Styles.Render("~/Content/bootstrap-datepicker.css")

    <script src="~/Scripts/moment-with-locales.min.js"></script>

    <script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd.mm.yyyy",
            autoclose: true,
        });
    });
    </script>
}

Tasks/asp/old hospital/АРМ робітника прийомного відділення/Views/Staff/StaffGrid.cshtml
@model IEnumerable<Business_Layer.DataModels.StaffDataModel>
@using GridMvc.Html
<meta name="viewport" content="width=device-width" />

<link href="~/Content/GridGround.css" rel="stylesheet" />
<div id="white">
    <center>
        <h2>Перелік працівників</h2>

        @Html.Grid(Model).SetLanguage("uk").Columns(columns =>
{
    columns.Add(data => data.Surname).Titled("ПІБ").RenderValueAs(o => o.Surname + " " + o.Name + " " + o.Middle_name).Filterable(true);
    columns.Add(data => data.Birthday).Format("{0:dd/MM/yyyy}").Titled("День народження").Sortable(true).Filterable(true);
    columns.Add(data => data.Employment_day).Format("{0:dd/MM/yyyy}").Titled("Дата наймання").Sortable(true).Filterable(true);
    columns.Add(data => data.Addresses).Titled("Адреса проживання").Sortable(true).Filterable(true);
    columns.Add(data => data.Phone_number).Titled("Номер телефону").Sortable(true).Filterable(true);
    columns.Add(data => data.Name_of_position).Titled("Посада").Sortable(true).Filterable(true);
    columns.Add()
                        .Encoded(false)
                        .Sanitized(false)
                        .SetWidth(30)
                        .RenderValueAs(o => Html.ActionLink("Редагувати", "EditStaff", new { id = o.Number_of_staff }));
    columns.Add()
                     .Encoded(false)
                     .Sanitized(false)
                     .SetWidth(30)
                     .RenderValueAs(o => Html.ActionLink("Видалити", "DeleteStaff", new { id = o.Number_of_staff }));
}).WithPaging(6).WithMultipleFilters()
    </center>
</div>
@section Scripts {

@Scripts.Render("~/bundles/mvcgrid")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Styles.Render("~/Content/bootstrap-datepicker.css")
    <link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="~/Scripts/jquery-2.2.3.min.js"></script>
<script type="text/javascript" src="~/Scripts/moment-with-locales.min.js"></script>
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/bootstrap-datepicker.js")
@Styles.Render("~/Content/bootstrap-datepicker.css")


<script type="text/javascript">
                    $(function () {
                        $('.datepicker').datepicker({
                            format: "dd.mm.yyyy",
                            autoclose: true,
                            language: 'ru'
                        });

                    });

                    $.fn.datepicker.dates['ru'] = {
                        days: ["Понеділок", "Вівторок", "Середа", "Четерг", "П'ятниця", "Субота", "Неділя"],
                        daysShort: ["Пон", "Вів", "Сер", "Чет", "П'ятн", "Суб", "Нед"],
                        daysMin: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
                        months: ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
                        monthsShort: ["Січ", "Лют", "Бер", "Квіт", "Трав", "Черв", "Лип", "Серп", "Верес", "Жовт", "Лист", "Груд"],
                        format: "mm.dd.yyyy",
                    };

                    $(function () {
                        $.validator.methods.date = function (value, element) {
                            if ($.browser.webkit) {
                                var d = new Date();
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                            }
                            else {
                                return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                            }
                        };
                    });
</script>
}